LOAD DATA LOCAL INFILE 'User.csv' INTO TABLE User FIELDS TERMINATED BY ',' ENCLOSED BY '"' LINES TERMINATED BY '\n';

LOAD DATA LOCAL INFILE 'Item.csv' INTO TABLE User FIELDS TERMINATED BY ',' ENCLOSED BY '"' LINES TERMINATED BY '\n';

LOAD DATA LOCAL INFILE 'ItemBids.csv' INTO TABLE User FIELDS TERMINATED BY ',' ENCLOSED BY '"' LINES TERMINATED BY '\n';

LOAD DATA LOCAL INFILE 'Bids.csv' INTO TABLE User FIELDS TERMINATED BY ',' ENCLOSED BY '"' LINES TERMINATED BY '\n';

LOAD DATA LOCAL INFILE 'Category.csv' INTO TABLE User FIELDS TERMINATED BY ',' ENCLOSED BY '"' LINES TERMINATED BY '\n';

LOAD DATA LOCAL INFILE 'ItemCategory.csv' INTO TABLE User FIELDS TERMINATED BY ',' ENCLOSED BY '"' LINES TERMINATED BY '\n';